services:

  tfm-postgres-db:
    image: postgres:17
    container_name: tfm-postgres-db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      PGHOST: "tfm-postgres-db"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER}"
      PGDATABASE: "${POSTGRES_DB}"
      BAK_FILE: "${DUMP_FILE}"

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/database/postgres/docker/adventure_works_dw_backup.bak:/${DUMP_FILE}
      - ./data/database/postgres/docker/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh


  tfm-chroma-db:
    image: chromadb/chroma:1.0.20
    container_name: tfm-chroma-db
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${CHROMA_LOCAL_PORT}:${CHROMA_SERVER_HTTP_PORT}"
    
    volumes:
      - ./data/embeddings/chroma:/data


volumes:
  pgdata:
  chroma_data: {}