-- ****************************************
-- Create Database
-- ****************************************


DROP DATABASE IF EXISTS adventure_works_dw;


CREATE DATABASE adventure_works_dw;

\c adventure_works_dw;

CREATE SCHEMA adventure_works;

DROP SCHEMA IF EXISTS public CASCADE;



-- ******************************************************
-- Create tables
-- ******************************************************

CREATE TABLE "adventure_works"."DimAccount" (
    "AccountKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ParentAccountKey" INT NULL,
    "AccountCodeAlternateKey" INT NULL,
    "ParentAccountCodeAlternateKey" INT NULL,
    "AccountDescription" VARCHAR(50) NULL,
    "AccountType" VARCHAR(50) NULL,
    "Operator" VARCHAR(50) NULL,
    "CustomMembers" VARCHAR(300) NULL,
    "ValueType" VARCHAR(50) NULL,
    "CustomMemberOptions" VARCHAR(200) NULL
);

CREATE TABLE "adventure_works"."DimCurrency" (
    "CurrencyKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "CurrencyAlternateKey" CHAR(3) NOT NULL,
    "CurrencyName" VARCHAR(50) NOT NULL
);

CREATE TABLE "adventure_works"."DimCustomer" (
    "CustomerKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "GeographyKey" INT NULL,
    "CustomerAlternateKey" VARCHAR(15) NOT NULL,
    "Title" VARCHAR(8) NULL,
    "FirstName" VARCHAR(50) NULL,
    "MiddleName" VARCHAR(50) NULL,
    "LastName" VARCHAR(50) NULL,
    "NameStyle" BOOLEAN NULL,
    "BirthDate" DATE NULL,
    "MaritalStatus" CHAR(1) NULL,
    "Suffix" VARCHAR(10) NULL,
    "Gender" VARCHAR(1) NULL,
    "EmailAddress" VARCHAR(50) NULL,
    "YearlyIncome" NUMERIC(19,4) NULL,
    "TotalChildren" SMALLINT NULL,
    "NumberChildrenAtHome" SMALLINT NULL,
    "EnglishEducation" VARCHAR(40) NULL,
    "SpanishEducation" VARCHAR(40) NULL,
    "FrenchEducation" VARCHAR(40) NULL,
    "EnglishOccupation" VARCHAR(100) NULL,
    "SpanishOccupation" VARCHAR(100) NULL,
    "FrenchOccupation" VARCHAR(100) NULL,
    "HouseOwnerFlag" CHAR(1) NULL,
    "NumberCarsOwned" SMALLINT NULL,
    "AddressLine1" VARCHAR(120) NULL,
    "AddressLine2" VARCHAR(120) NULL,
    "Phone" VARCHAR(20) NULL,
    "DateFirstPurchase" DATE NULL,
    "CommuteDistance" VARCHAR(15) NULL
);

CREATE TABLE "adventure_works"."DimDate" (
    "DateKey" INT NOT NULL,
    "FullDateAlternateKey" DATE NOT NULL,
    "DayNumberOfWeek" SMALLINT NOT NULL,
    "EnglishDayNameOfWeek" VARCHAR(10) NOT NULL,
    "SpanishDayNameOfWeek" VARCHAR(10) NOT NULL,
    "FrenchDayNameOfWeek" VARCHAR(10) NOT NULL,
    "DayNumberOfMonth" SMALLINT NOT NULL,
    "DayNumberOfYear" SMALLINT NOT NULL,
    "WeekNumberOfYear" SMALLINT NOT NULL,
    "EnglishMonthName" VARCHAR(10) NOT NULL,
    "SpanishMonthName" VARCHAR(10) NOT NULL,
    "FrenchMonthName" VARCHAR(10) NOT NULL,
    "MonthNumberOfYear" SMALLINT NOT NULL,
    "CalendarQuarter" SMALLINT NOT NULL,
    "CalendarYear" SMALLINT NOT NULL,
    "CalendarSemester" SMALLINT NOT NULL,
    "FiscalQuarter" SMALLINT NOT NULL,
    "FiscalYear" SMALLINT NOT NULL,
    "FiscalSemester" SMALLINT NOT NULL
);

CREATE TABLE "adventure_works"."DimDepartmentGroup" (
    "DepartmentGroupKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ParentDepartmentGroupKey" INT NULL,
    "DepartmentGroupName" VARCHAR(50) NULL
);

CREATE TABLE "adventure_works"."DimEmployee" (
    "EmployeeKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ParentEmployeeKey" INT NULL,
    "EmployeeNationalIDAlternateKey" VARCHAR(15) NULL,
    "ParentEmployeeNationalIDAlternateKey" VARCHAR(15) NULL,
    "SalesTerritoryKey" INT NULL,
    "FirstName" VARCHAR(50) NOT NULL,
    "LastName" VARCHAR(50) NOT NULL,
    "MiddleName" VARCHAR(50) NULL,
    "NameStyle" BOOLEAN NOT NULL,
    "Title" VARCHAR(50) NULL,
    "HireDate" DATE NULL,
    "BirthDate" DATE NULL,
    "LoginID" VARCHAR(256) NULL,
    "EmailAddress" VARCHAR(50) NULL,
    "Phone" VARCHAR(25) NULL,
    "MaritalStatus" CHAR(1) NULL,
    "EmergencyContactName" VARCHAR(50) NULL,
    "EmergencyContactPhone" VARCHAR(25) NULL,
    "SalariedFlag" BOOLEAN NULL,
    "Gender" CHAR(1) NULL,
    "PayFrequency" SMALLINT NULL,
    "BaseRate" NUMERIC(19,4) NULL,
    "VacationHours" SMALLINT NULL,
    "SickLeaveHours" SMALLINT NULL,
    "CurrentFlag" BOOLEAN NOT NULL,
    "SalesPersonFlag" BOOLEAN NOT NULL,
    "DepartmentName" VARCHAR(50) NULL,
    "StartDate" DATE NULL,
    "EndDate" DATE NULL,
    "Status" VARCHAR(50) NULL,
    "EmployeePhoto" BYTEA NULL
);

CREATE TABLE "adventure_works"."DimGeography" (
    "GeographyKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "City" VARCHAR(30) NULL,
    "StateProvinceCode" VARCHAR(3) NULL,
    "StateProvinceName" VARCHAR(50) NULL,
    "CountryRegionCode" VARCHAR(3) NULL,
    "EnglishCountryRegionName" VARCHAR(50) NULL,
    "SpanishCountryRegionName" VARCHAR(50) NULL,
    "FrenchCountryRegionName" VARCHAR(50) NULL,
    "PostalCode" VARCHAR(15) NULL,
    "SalesTerritoryKey" INT NULL,
    "IpAddressLocator" VARCHAR(15) NULL
);

CREATE TABLE "adventure_works"."DimOrganization" (
    "OrganizationKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ParentOrganizationKey" INT NULL,
    "PercentageOfOwnership" VARCHAR(16) NULL,
    "OrganizationName" VARCHAR(50) NULL,
    "CurrencyKey" INT NULL
);

CREATE TABLE "adventure_works"."DimProduct" (
    "ProductKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ProductAlternateKey" VARCHAR(25) NULL,
    "ProductSubcategoryKey" INT NULL,
    "WeightUnitMeasureCode" CHAR(3) NULL,
    "SizeUnitMeasureCode" CHAR(3) NULL,
    "EnglishProductName" VARCHAR(50) NOT NULL,
    "SpanishProductName" VARCHAR(50) NOT NULL,
    "FrenchProductName" VARCHAR(50) NOT NULL,
    "StandardCost" NUMERIC(19,4) NULL,
    "FinishedGoodsFlag" BOOLEAN NOT NULL,
    "Color" VARCHAR(15) NOT NULL,
    "SafetyStockLevel" SMALLINT NULL,
    "ReorderPoint" SMALLINT NULL,
    "ListPrice" NUMERIC(19,4) NULL,
    "Size" VARCHAR(50) NULL,
    "SizeRange" VARCHAR(50) NULL,
    "Weight" REAL NULL,
    "DaysToManufacture" INT NULL,
    "ProductLine" CHAR(2) NULL,
    "DealerPrice" NUMERIC(19,4) NULL,
    "Class" CHAR(2) NULL,
    "Style" CHAR(2) NULL,
    "ModelName" VARCHAR(50) NULL,
    "LargePhoto" BYTEA NULL,
    "EnglishDescription" VARCHAR(400) NULL,
    "FrenchDescription" VARCHAR(400) NULL,
    "ChineseDescription" VARCHAR(400) NULL,
    "ArabicDescription" VARCHAR(400) NULL,
    "HebrewDescription" VARCHAR(400) NULL,
    "ThaiDescription" VARCHAR(400) NULL,
    "GermanDescription" VARCHAR(400) NULL,
    "JapaneseDescription" VARCHAR(400) NULL,
    "TurkishDescription" VARCHAR(400) NULL,
    "StartDate" TIMESTAMP NULL,
    "EndDate" TIMESTAMP NULL,
    "Status" VARCHAR(7) NULL
);

CREATE TABLE "adventure_works"."DimProductCategory" (
    "ProductCategoryKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ProductCategoryAlternateKey" INT NULL,
    "EnglishProductCategoryName" VARCHAR(50) NOT NULL,
    "SpanishProductCategoryName" VARCHAR(50) NOT NULL,
    "FrenchProductCategoryName" VARCHAR(50) NOT NULL
);

CREATE TABLE "adventure_works"."DimProductSubcategory" (
    "ProductSubcategoryKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ProductSubcategoryAlternateKey" INT NULL,
    "EnglishProductSubcategoryName" VARCHAR(50) NOT NULL,
    "SpanishProductSubcategoryName" VARCHAR(50) NOT NULL,
    "FrenchProductSubcategoryName" VARCHAR(50) NOT NULL,
    "ProductCategoryKey" INT NULL
);

CREATE TABLE "adventure_works"."DimPromotion" (
    "PromotionKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "PromotionAlternateKey" INT NULL,
    "EnglishPromotionName" VARCHAR(255) NULL,
    "SpanishPromotionName" VARCHAR(255) NULL,
    "FrenchPromotionName" VARCHAR(255) NULL,
    "DiscountPct" REAL NULL,
    "EnglishPromotionType" VARCHAR(50) NULL,
    "SpanishPromotionType" VARCHAR(50) NULL,
    "FrenchPromotionType" VARCHAR(50) NULL,
    "EnglishPromotionCategory" VARCHAR(50) NULL,
    "SpanishPromotionCategory" VARCHAR(50) NULL,
    "FrenchPromotionCategory" VARCHAR(50) NULL,
    "StartDate" TIMESTAMP NOT NULL,
    "EndDate" TIMESTAMP NULL,
    "MinQty" INT NULL,
    "MaxQty" INT NULL
);

CREATE TABLE "adventure_works"."DimReseller" (
    "ResellerKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "GeographyKey" INT NULL,
    "ResellerAlternateKey" VARCHAR(15) NULL,
    "Phone" VARCHAR(25) NULL,
    "BusinessType" VARCHAR(20) NOT NULL,
    "ResellerName" VARCHAR(50) NOT NULL,
    "NumberEmployees" INT NULL,
    "OrderFrequency" CHAR(1) NULL,
    "OrderMonth" SMALLINT NULL,
    "FirstOrderYear" INT NULL,
    "LastOrderYear" INT NULL,
    "ProductLine" VARCHAR(50) NULL,
    "AddressLine1" VARCHAR(60) NULL,
    "AddressLine2" VARCHAR(60) NULL,
    "AnnualSales" NUMERIC(19,4) NULL,
    "BankName" VARCHAR(50) NULL,
    "MinPaymentType" SMALLINT NULL,
    "MinPaymentAmount" NUMERIC(19,4) NULL,
    "AnnualRevenue" NUMERIC(19,4) NULL,
    "YearOpened" INT NULL
);

CREATE TABLE "adventure_works"."DimSalesReason" (
    "SalesReasonKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "SalesReasonAlternateKey" INT NOT NULL,
    "SalesReasonName" VARCHAR(50) NOT NULL,
    "SalesReasonReasonType" VARCHAR(50) NOT NULL
);

CREATE TABLE "adventure_works"."DimSalesTerritory" (
    "SalesTerritoryKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "SalesTerritoryAlternateKey" INT NULL,
    "SalesTerritoryRegion" VARCHAR(50) NOT NULL,
    "SalesTerritoryCountry" VARCHAR(50) NOT NULL,
    "SalesTerritoryGroup" VARCHAR(50) NULL,
    "SalesTerritoryImage" BYTEA NULL
);

CREATE TABLE "adventure_works"."DimScenario" (
    "ScenarioKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ScenarioName" VARCHAR(50) NULL
);

CREATE TABLE "adventure_works"."FactAdditionalInternationalProductDescription" (
    "ProductKey" INT NOT NULL,
    "CultureName" VARCHAR(50) NOT NULL,
    "ProductDescription" TEXT NOT NULL
);

CREATE TABLE "adventure_works"."FactCallCenter" (
    "FactCallCenterID" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "DateKey" INT NOT NULL,
    "WageType" VARCHAR(15) NOT NULL,
    "Shift" VARCHAR(20) NOT NULL,
    "LevelOneOperators" SMALLINT NOT NULL,
    "LevelTwoOperators" SMALLINT NOT NULL,
    "TotalOperators" SMALLINT NOT NULL,
    "Calls" INT NOT NULL,
    "AutomaticResponses" INT NOT NULL,
    "Orders" INT NOT NULL,
    "IssuesRaised" SMALLINT NOT NULL,
    "AverageTimePerIssue" SMALLINT NOT NULL,
    "ServiceGrade" REAL NOT NULL,
    "Date" TIMESTAMP NULL
);

CREATE TABLE "adventure_works"."FactCurrencyRate" (
    "CurrencyKey" INT NOT NULL,
    "DateKey" INT NOT NULL,
    "AverageRate" REAL NOT NULL,
    "EndOfDayRate" REAL NOT NULL,
    "Date" TIMESTAMP NULL
);

CREATE TABLE "adventure_works"."FactFinance" (
    "FinanceKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "DateKey" INT NOT NULL,
    "OrganizationKey" INT NOT NULL,
    "DepartmentGroupKey" INT NOT NULL,
    "ScenarioKey" INT NOT NULL,
    "AccountKey" INT NOT NULL,
    "Amount" REAL NOT NULL,
    "Date" TIMESTAMP NULL
);

CREATE TABLE "adventure_works"."FactInternetSales" (
    "ProductKey" INT NOT NULL,
    "OrderDateKey" INT NOT NULL,
    "DueDateKey" INT NOT NULL,
    "ShipDateKey" INT NOT NULL,
    "CustomerKey" INT NOT NULL,
    "PromotionKey" INT NOT NULL,
    "CurrencyKey" INT NOT NULL,
    "SalesTerritoryKey" INT NOT NULL,
    "SalesOrderNumber" VARCHAR(20) NOT NULL,
    "SalesOrderLineNumber" SMALLINT NOT NULL,
    "RevisionNumber" SMALLINT NOT NULL,
    "OrderQuantity" SMALLINT NOT NULL,
    "UnitPrice" NUMERIC(19,4) NOT NULL,
    "ExtendedAmount" NUMERIC(19,4) NOT NULL,
    "UnitPriceDiscountPct" REAL NOT NULL,
    "DiscountAmount" REAL NOT NULL,
    "ProductStandardCost" NUMERIC(19,4) NOT NULL,
    "TotalProductCost" NUMERIC(19,4) NOT NULL,
    "SalesAmount" NUMERIC(19,4) NOT NULL,
    "TaxAmt" NUMERIC(19,4) NOT NULL,
    "Freight" NUMERIC(19,4) NOT NULL,
    "CarrierTrackingNumber" VARCHAR(25) NULL,
    "CustomerPONumber" VARCHAR(25) NULL,
    "OrderDate" TIMESTAMP NULL,
    "DueDate" TIMESTAMP NULL,
    "ShipDate" TIMESTAMP NULL
);

CREATE TABLE "adventure_works"."FactInternetSalesReason" (
    "SalesOrderNumber" VARCHAR(20) NOT NULL,
    "SalesOrderLineNumber" SMALLINT NOT NULL,
    "SalesReasonKey" INT NOT NULL
);

CREATE TABLE "adventure_works"."FactProductInventory" (
    "ProductKey" INT NOT NULL,
    "DateKey" INT NOT NULL,
    "MovementDate" DATE NOT NULL,
    "UnitCost" NUMERIC(19,4) NOT NULL,
    "UnitsIn" INT NOT NULL,
    "UnitsOut" INT NOT NULL,
    "UnitsBalance" INT NOT NULL
);

CREATE TABLE "adventure_works"."FactResellerSales" (
    "ProductKey" INT NOT NULL,
    "OrderDateKey" INT NOT NULL,
    "DueDateKey" INT NOT NULL,
    "ShipDateKey" INT NOT NULL,
    "ResellerKey" INT NOT NULL,
    "EmployeeKey" INT NOT NULL,
    "PromotionKey" INT NOT NULL,
    "CurrencyKey" INT NOT NULL,
    "SalesTerritoryKey" INT NOT NULL,
    "SalesOrderNumber" VARCHAR(20) NOT NULL,
    "SalesOrderLineNumber" SMALLINT NOT NULL,
    "RevisionNumber" SMALLINT NULL,
    "OrderQuantity" SMALLINT NULL,
    "UnitPrice" NUMERIC(19,4) NULL,
    "ExtendedAmount" NUMERIC(19,4) NULL,
    "UnitPriceDiscountPct" REAL NULL,
    "DiscountAmount" REAL NULL,
    "ProductStandardCost" NUMERIC(19,4) NULL,
    "TotalProductCost" NUMERIC(19,4) NULL,
    "SalesAmount" NUMERIC(19,4) NULL,
    "TaxAmt" NUMERIC(19,4) NULL,
    "Freight" NUMERIC(19,4) NULL,
    "CarrierTrackingNumber" VARCHAR(25) NULL,
    "CustomerPONumber" VARCHAR(25) NULL,
    "OrderDate" TIMESTAMP NULL,
    "DueDate" TIMESTAMP NULL,
    "ShipDate" TIMESTAMP NULL
);

CREATE TABLE "adventure_works"."FactSalesQuota" (
    "SalesQuotaKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "EmployeeKey" INT NOT NULL,
    "DateKey" INT NOT NULL,
    "CalendarYear" SMALLINT NOT NULL,
    "CalendarQuarter" SMALLINT NOT NULL,
    "SalesAmountQuota" NUMERIC(19,4) NOT NULL,
    "Date" TIMESTAMP NULL
);

CREATE TABLE "adventure_works"."FactSurveyResponse" (
    "SurveyResponseKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "DateKey" INT NOT NULL,
    "CustomerKey" INT NOT NULL,
    "ProductCategoryKey" INT NOT NULL,
    "EnglishProductCategoryName" VARCHAR(50) NOT NULL,
    "ProductSubcategoryKey" INT NOT NULL,
    "EnglishProductSubcategoryName" VARCHAR(50) NOT NULL,
    "Date" TIMESTAMP NULL
);

CREATE TABLE "adventure_works"."NewFactCurrencyRate" (
    "AverageRate" REAL NULL,
    "CurrencyID" VARCHAR(3) NULL,
    "CurrencyDate" DATE NULL,
    "EndOfDayRate" REAL NULL,
    "CurrencyKey" INT NULL,
    "DateKey" INT NULL
);

CREATE TABLE "adventure_works"."ProspectiveBuyer" (
    "ProspectiveBuyerKey" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ProspectAlternateKey" VARCHAR(15) NULL,
    "FirstName" VARCHAR(50) NULL,
    "MiddleName" VARCHAR(50) NULL,
    "LastName" VARCHAR(50) NULL,
    "BirthDate" TIMESTAMP NULL,
    "MaritalStatus" CHAR(1) NULL,
    "Gender" VARCHAR(1) NULL,
    "EmailAddress" VARCHAR(50) NULL,
    "YearlyIncome" NUMERIC(19,4) NULL,
    "TotalChildren" SMALLINT NULL,
    "NumberChildrenAtHome" SMALLINT NULL,
    "Education" VARCHAR(40) NULL,
    "Occupation" VARCHAR(100) NULL,
    "HouseOwnerFlag" CHAR(1) NULL,
    "NumberCarsOwned" SMALLINT NULL,
    "AddressLine1" VARCHAR(120) NULL,
    "AddressLine2" VARCHAR(120) NULL,
    "City" VARCHAR(30) NULL,
    "StateProvinceCode" VARCHAR(3) NULL,
    "PostalCode" VARCHAR(15) NULL,
    "Phone" VARCHAR(20) NULL,
    "Salutation" VARCHAR(8) NULL,
    "Unknown" INT NULL
)



-- ******************************************************
-- Load data
-- ******************************************************

COPY "adventure_works"."DimAccount" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimAccount.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimCurrency" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimCurrency.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimCustomer" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimCustomer.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimDate" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimDate.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimDepartmentGroup" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimDepartmentGroup.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimEmployee" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimEmployee.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimGeography" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimGeography.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimOrganization" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimOrganization.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimProduct" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimProduct.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimProductCategory" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimProductCategory.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimProductSubcategory" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimProductSubcategory.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimPromotion" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimPromotion.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimReseller" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimReseller.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimSalesReason" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimSalesReason.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimSalesTerritory" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimSalesTerritory.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."DimScenario" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/DimScenario.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactAdditionalInternationalProductDescription" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactAdditionalInternationalProductDescription.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactCallCenter" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactCallCenter.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactCurrencyRate" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactCurrencyRate.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactFinance" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactFinance.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactInternetSales" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactInternetSales.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactInternetSalesReason" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactInternetSalesReason.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactProductInventory" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactProductInventory.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactResellerSales" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactResellerSales.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactSalesQuota" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactSalesQuota.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."FactSurveyResponse" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/FactSurveyResponse.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."NewFactCurrencyRate" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/NewFactCurrencyRate.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."ProspectiveBuyer" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/ProspectiveBuyer.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);

COPY "adventure_works"."sysdiagrams" FROM 'C:/python/ucm-tfm-grupo-4/data/database/postgres/sysdiagrams.csv' WITH (
    DELIMITER '|',
    FORMAT CSV,
    HEADER FALSE,
    ENCODING 'UTF8'
);




-- ******************************************************
-- Add Primary Keys
-- ******************************************************

ALTER TABLE "adventure_works"."DimAccount"
ADD CONSTRAINT "PK_DimAccount" PRIMARY KEY ("AccountKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimCurrency"
    ADD CONSTRAINT "PK_DimCurrency_CurrencyKey" PRIMARY KEY ("CurrencyKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimCustomer"
    ADD CONSTRAINT "PK_DimCustomer_CustomerKey" PRIMARY KEY ("CustomerKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimDate"
ADD CONSTRAINT "PK_DimDate_DateKey" PRIMARY KEY ("DateKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimDepartmentGroup"
    ADD CONSTRAINT "PK_DimDepartmentGroup" PRIMARY KEY ("DepartmentGroupKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimEmployee"
    ADD CONSTRAINT "PK_DimEmployee_EmployeeKey" PRIMARY KEY ("EmployeeKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimGeography"
    ADD CONSTRAINT "PK_DimGeography_GeographyKey" PRIMARY KEY ("GeographyKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimOrganization"
ADD CONSTRAINT "PK_DimOrganization" PRIMARY KEY ("OrganizationKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimProduct"
ADD CONSTRAINT "PK_DimProduct_ProductKey" PRIMARY KEY ("ProductKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimProductCategory"
    ADD CONSTRAINT "PK_DimProductCategory_ProductCategoryKey" PRIMARY KEY ("ProductCategoryKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimProductSubcategory"
    ADD CONSTRAINT "PK_DimProductSubcategory_ProductSubcategoryKey" PRIMARY KEY ("ProductSubcategoryKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimPromotion"
    ADD CONSTRAINT "PK_DimPromotion_PromotionKey" PRIMARY KEY ("PromotionKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimReseller"
    ADD CONSTRAINT "PK_DimReseller_ResellerKey" PRIMARY KEY ("ResellerKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimSalesReason"
    ADD CONSTRAINT "PK_DimSalesReason_SalesReasonKey" PRIMARY KEY ("SalesReasonKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DatabaseLog"
    ADD CONSTRAINT "PK_DatabaseLog_DatabaseLogID" PRIMARY KEY ("DatabaseLogID" NULLS FIRST)

ALTER TABLE "adventure_works"."DimSalesTerritory"
    ADD CONSTRAINT "PK_DimSalesTerritory_SalesTerritoryKey" PRIMARY KEY ("SalesTerritoryKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimScenario"
ADD CONSTRAINT "PK_DimScenario" PRIMARY KEY ("ScenarioKey" NULLS FIRST)

ALTER TABLE "adventure_works"."FactAdditionalInternationalProductDescription"
    ADD CONSTRAINT "PK_FactAdditionalInternationalProductDescription_ProductKey_CultureName" PRIMARY KEY ("ProductKey" NULLS FIRST, "CultureName" NULLS FIRST)

ALTER TABLE "adventure_works"."FactCallCenter"
    ADD CONSTRAINT "PK_FactCallCenter_FactCallCenterID" PRIMARY KEY ("FactCallCenterID" NULLS FIRST)

ALTER TABLE "adventure_works"."FactCurrencyRate"
    ADD CONSTRAINT "PK_FactCurrencyRate_CurrencyKey_DateKey" PRIMARY KEY ("CurrencyKey" NULLS FIRST, "DateKey" NULLS FIRST)

ALTER TABLE "adventure_works"."FactInternetSales"
    ADD CONSTRAINT "PK_FactInternetSales_SalesOrderNumber_SalesOrderLineNumber" PRIMARY KEY ("SalesOrderNumber" NULLS FIRST, "SalesOrderLineNumber" NULLS FIRST)

ALTER TABLE "adventure_works"."FactInternetSalesReason"
    ADD CONSTRAINT "PK_FactInternetSalesReason_SalesOrderNumber_SalesOrderLineNumber_SalesReasonKey" PRIMARY KEY ("SalesOrderNumber" NULLS FIRST, "SalesOrderLineNumber" NULLS FIRST, "SalesReasonKey" NULLS FIRST)

ALTER TABLE "adventure_works"."FactProductInventory"
    ADD CONSTRAINT "PK_FactProductInventory" PRIMARY KEY ("ProductKey" NULLS FIRST, "DateKey" NULLS FIRST)

ALTER TABLE "adventure_works"."FactResellerSales"
    ADD CONSTRAINT "PK_FactResellerSales_SalesOrderNumber_SalesOrderLineNumber" PRIMARY KEY ("SalesOrderNumber" NULLS FIRST, "SalesOrderLineNumber" NULLS FIRST)

ALTER TABLE "adventure_works"."FactSalesQuota"
    ADD CONSTRAINT "PK_FactSalesQuota_SalesQuotaKey" PRIMARY KEY ("SalesQuotaKey" NULLS FIRST)

ALTER TABLE "adventure_works"."FactSurveyResponse"
    ADD CONSTRAINT "PK_FactSurveyResponse_SurveyResponseKey" PRIMARY KEY ("SurveyResponseKey" NULLS FIRST)

ALTER TABLE "adventure_works"."ProspectiveBuyer"
    ADD CONSTRAINT "PK_ProspectiveBuyer_ProspectiveBuyerKey" PRIMARY KEY ("ProspectiveBuyerKey" NULLS FIRST)



-- ******************************************************
-- Add Indexes
-- ******************************************************

CREATE UNIQUE INDEX "AK_DimCurrency_CurrencyAlternateKey" ON "adventure_works"."DimCurrency"("CurrencyAlternateKey" NULLS FIRST)

CREATE UNIQUE INDEX "IX_DimCustomer_CustomerAlternateKey" ON "adventure_works"."DimCustomer"("CustomerAlternateKey" NULLS FIRST)

CREATE UNIQUE INDEX "AK_DimDate_FullDateAlternateKey" ON "adventure_works"."DimDate"("FullDateAlternateKey" NULLS FIRST)

ALTER TABLE "adventure_works"."DimProduct"
    ADD CONSTRAINT "AK_DimProduct_ProductAlternateKey_StartDate" UNIQUE ("ProductAlternateKey" ASC NULLS FIRST,
    "StartDate" ASC NULLS FIRST)
 /* ***** Object:  Index [AK_DimProduct_ProductAlternateKey_StartDate]    Script Date: 7/8/2016 2:39:08 PM ***** */

ALTER TABLE "adventure_works"."DimProductCategory"
    ADD CONSTRAINT "AK_DimProductCategory_ProductCategoryAlternateKey" UNIQUE ("ProductCategoryAlternateKey" ASC NULLS FIRST)
 /* ***** Object:  Index [AK_DimProductCategory_ProductCategoryAlternateKey]    Script Date: 7/8/2016 2:40:13 PM ***** */

ALTER TABLE "adventure_works"."DimProductSubcategory"
    ADD CONSTRAINT "AK_DimProductSubcategory_ProductSubcategoryAlternateKey" UNIQUE ("ProductSubcategoryAlternateKey" ASC NULLS FIRST)
 /* ***** Object:  Index [AK_DimProductSubcategory_ProductSubcategoryAlternateKey]    Script Date: 7/8/2016 2:40:37 PM ***** */

ALTER TABLE "adventure_works"."DimPromotion"
    ADD CONSTRAINT "AK_DimPromotion_PromotionAlternateKey" UNIQUE ("PromotionAlternateKey" ASC NULLS FIRST)
 /* ***** Object:  Index [AK_DimPromotion_PromotionAlternateKey]    Script Date: 7/8/2016 2:41:46 PM ***** */

ALTER TABLE "adventure_works"."DimReseller"
    ADD CONSTRAINT "AK_DimReseller_ResellerAlternateKey" UNIQUE ("ResellerAlternateKey" ASC NULLS FIRST)
 /* ***** Object:  Index [AK_DimReseller_ResellerAlternateKey]    Script Date: 7/8/2016 2:42:07 PM ***** */

ALTER TABLE "adventure_works"."DimSalesTerritory"
    ADD CONSTRAINT "AK_DimSalesTerritory_SalesTerritoryAlternateKey" UNIQUE ("SalesTerritoryAlternateKey" ASC NULLS FIRST)
 /* ***** Object:  Index [AK_DimSalesTerritory_SalesTerritoryAlternateKey]    Script Date: 7/8/2016 2:43:13 PM ***** */

ALTER TABLE "adventure_works"."FactCallCenter"
    ADD CONSTRAINT "AK_FactCallCenter_DateKey_Shift" UNIQUE ("DateKey" ASC NULLS FIRST,
    "Shift" ASC NULLS FIRST)
 /* ***** Object:  Index [AK_FactCallCenter_DateKey_Shift]    Script Date: 7/8/2016 2:43:49 PM ***** */

CREATE UNIQUE INDEX "UK_principal_name" ON "adventure_works"."sysdiagrams"("principal_id" NULLS FIRST, "name" NULLS FIRST)



-- ****************************************
-- Create Foreign key constraints
-- ****************************************

ALTER TABLE "adventure_works"."DimAccount"
    ADD CONSTRAINT "FK_DimAccount_DimAccount" FOREIGN KEY ("ParentAccountKey") REFERENCES "adventure_works"."DimAccount" (
        "AccountKey"
    )

ALTER TABLE "adventure_works"."DimCustomer"
    ADD CONSTRAINT "FK_DimCustomer_DimGeography" FOREIGN KEY ("GeographyKey") REFERENCES "adventure_works"."DimGeography" (
        "GeographyKey"
    )

ALTER TABLE "adventure_works"."DimDepartmentGroup"
    ADD CONSTRAINT "FK_DimDepartmentGroup_DimDepartmentGroup" FOREIGN KEY ("ParentDepartmentGroupKey") REFERENCES "adventure_works"."DimDepartmentGroup" (
        "DepartmentGroupKey"
    )

ALTER TABLE "adventure_works"."DimEmployee"
    ADD CONSTRAINT "FK_DimEmployee_DimSalesTerritory" FOREIGN KEY ("SalesTerritoryKey") REFERENCES "adventure_works"."DimSalesTerritory" (
        "SalesTerritoryKey"
    ),
    CONSTRAINT "FK_DimEmployee_DimEmployee" FOREIGN KEY ("ParentEmployeeKey") REFERENCES "adventure_works"."DimEmployee" (
        "EmployeeKey"
    )

ALTER TABLE "adventure_works"."DimGeography"
    ADD CONSTRAINT "FK_DimGeography_DimSalesTerritory" FOREIGN KEY ("SalesTerritoryKey") REFERENCES "adventure_works"."DimSalesTerritory" (
        "SalesTerritoryKey"
    )

ALTER TABLE "adventure_works"."DimOrganization"
    ADD CONSTRAINT "FK_DimOrganization_DimCurrency" FOREIGN KEY ("CurrencyKey") REFERENCES "adventure_works"."DimCurrency" (
        "CurrencyKey"
    ),
    CONSTRAINT "FK_DimOrganization_DimOrganization" FOREIGN KEY ("ParentOrganizationKey") REFERENCES "adventure_works"."DimOrganization" (
        "OrganizationKey"
    )

ALTER TABLE "adventure_works"."DimProduct"
    ADD CONSTRAINT "FK_DimProduct_DimProductSubcategory" FOREIGN KEY ("ProductSubcategoryKey") REFERENCES "adventure_works"."DimProductSubcategory" (
        "ProductSubcategoryKey"
    )

ALTER TABLE "adventure_works"."DimProductSubcategory"
    ADD CONSTRAINT "FK_DimProductSubcategory_DimProductCategory" FOREIGN KEY ("ProductCategoryKey") REFERENCES "adventure_works"."DimProductCategory" (
        "ProductCategoryKey"
    )

ALTER TABLE "adventure_works"."DimReseller"
    ADD CONSTRAINT "FK_DimReseller_DimGeography" FOREIGN KEY ("GeographyKey") REFERENCES "adventure_works"."DimGeography" (
        "GeographyKey"
    )

ALTER TABLE "adventure_works"."FactCallCenter"
    ADD CONSTRAINT "FK_FactCallCenter_DimDate" FOREIGN KEY ("DateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    )

ALTER TABLE "adventure_works"."FactCurrencyRate"
    ADD CONSTRAINT "FK_FactCurrencyRate_DimDate" FOREIGN KEY ("DateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactCurrencyRate_DimCurrency" FOREIGN KEY ("CurrencyKey") REFERENCES "adventure_works"."DimCurrency" (
        "CurrencyKey"
    )

ALTER TABLE "adventure_works"."FactFinance"
    ADD CONSTRAINT "FK_FactFinance_DimScenario" FOREIGN KEY ("ScenarioKey") REFERENCES "adventure_works"."DimScenario" (
        "ScenarioKey"
    ),
    CONSTRAINT "FK_FactFinance_DimOrganization" FOREIGN KEY ("OrganizationKey") REFERENCES "adventure_works"."DimOrganization" (
        "OrganizationKey"
    ),
    CONSTRAINT "FK_FactFinance_DimDepartmentGroup" FOREIGN KEY ("DepartmentGroupKey") REFERENCES "adventure_works"."DimDepartmentGroup" (
        "DepartmentGroupKey"
    ),
    CONSTRAINT "FK_FactFinance_DimDate" FOREIGN KEY ("DateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactFinance_DimAccount" FOREIGN KEY ("AccountKey") REFERENCES "adventure_works"."DimAccount" (
        "AccountKey"
    )

ALTER TABLE "adventure_works"."FactInternetSales"
    ADD CONSTRAINT "FK_FactInternetSales_DimCurrency" FOREIGN KEY ("CurrencyKey") REFERENCES "adventure_works"."DimCurrency" (
        "CurrencyKey"
    ),
    CONSTRAINT "FK_FactInternetSales_DimCustomer" FOREIGN KEY ("CustomerKey") REFERENCES "adventure_works"."DimCustomer" (
        "CustomerKey"
    ),
    CONSTRAINT "FK_FactInternetSales_DimDate" FOREIGN KEY ("OrderDateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactInternetSales_DimDate1" FOREIGN KEY ("DueDateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactInternetSales_DimDate2" FOREIGN KEY ("ShipDateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactInternetSales_DimProduct" FOREIGN KEY ("ProductKey") REFERENCES "adventure_works"."DimProduct" (
        "ProductKey"
    ),
    CONSTRAINT "FK_FactInternetSales_DimPromotion" FOREIGN KEY ("PromotionKey") REFERENCES "adventure_works"."DimPromotion" (
        "PromotionKey"
    ),
    CONSTRAINT "FK_FactInternetSales_DimSalesTerritory" FOREIGN KEY ("SalesTerritoryKey") REFERENCES "adventure_works"."DimSalesTerritory" (
        "SalesTerritoryKey"
    )

ALTER TABLE "adventure_works"."FactInternetSalesReason"
    ADD CONSTRAINT "FK_FactInternetSalesReason_FactInternetSales" FOREIGN KEY ("SalesOrderNumber", "SalesOrderLineNumber") REFERENCES "adventure_works"."FactInternetSales" (
        "SalesOrderNumber",
        "SalesOrderLineNumber"
    ),
    CONSTRAINT "FK_FactInternetSalesReason_DimSalesReason" FOREIGN KEY ("SalesReasonKey") REFERENCES "adventure_works"."DimSalesReason" (
        "SalesReasonKey"
    )

ALTER TABLE "adventure_works"."FactProductInventory"
    ADD CONSTRAINT "FK_FactProductInventory_DimDate" FOREIGN KEY ("DateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactProductInventory_DimProduct" FOREIGN KEY ("ProductKey") REFERENCES "adventure_works"."DimProduct" (
        "ProductKey"
    )

ALTER TABLE "adventure_works"."FactResellerSales"
    ADD CONSTRAINT "FK_FactResellerSales_DimCurrency" FOREIGN KEY ("CurrencyKey") REFERENCES "adventure_works"."DimCurrency" (
        "CurrencyKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimDate" FOREIGN KEY ("OrderDateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimDate1" FOREIGN KEY ("DueDateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimDate2" FOREIGN KEY ("ShipDateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimEmployee" FOREIGN KEY ("EmployeeKey") REFERENCES "adventure_works"."DimEmployee" (
        "EmployeeKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimProduct" FOREIGN KEY ("ProductKey") REFERENCES "adventure_works"."DimProduct" (
        "ProductKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimPromotion" FOREIGN KEY ("PromotionKey") REFERENCES "adventure_works"."DimPromotion" (
        "PromotionKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimReseller" FOREIGN KEY ("ResellerKey") REFERENCES "adventure_works"."DimReseller" (
        "ResellerKey"
    ),
    CONSTRAINT "FK_FactResellerSales_DimSalesTerritory" FOREIGN KEY ("SalesTerritoryKey") REFERENCES "adventure_works"."DimSalesTerritory" (
        "SalesTerritoryKey"
    )

ALTER TABLE "adventure_works"."FactSalesQuota"
    ADD CONSTRAINT "FK_FactSalesQuota_DimEmployee" FOREIGN KEY ("EmployeeKey") REFERENCES "adventure_works"."DimEmployee" (
        "EmployeeKey"
    ),
    CONSTRAINT "FK_FactSalesQuota_DimDate" FOREIGN KEY ("DateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    )

ALTER TABLE "adventure_works"."FactSurveyResponse"
    ADD CONSTRAINT "FK_FactSurveyResponse_DateKey" FOREIGN KEY ("DateKey") REFERENCES "adventure_works"."DimDate" (
        "DateKey"
    ),
    CONSTRAINT "FK_FactSurveyResponse_CustomerKey" FOREIGN KEY ("CustomerKey") REFERENCES "adventure_works"."DimCustomer" (
        "CustomerKey"
    )



